export const IMG_CDN_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" ;


export const restaurantList = [
    {
      info: {
        id: "10894",
        name: "Pizza Hut",
        cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
        locality: "2nd Stage",
        areaName: "BTM Layout",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.1,
        parentId: "721",
        avgRatingString: "4.1",
        totalRatingsString: "10K+",
        deliveryTime: 31,
      },
    },
    {
      info: {
        id: "211192",
        name: "La Pino'z Pizza",
        cloudinaryImageId: "lczhp9lptdzbqn09nfns",
        locality: "2nd Stage",
        areaName: "BTM Layout",
        costForTwo: "₹250 for two",
        cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
        avgRating: 4,
        parentId: "4961",
        avgRatingString: "4.0",
        totalRatingsString: "10K+",
        deliveryTime: 28,
      },
    },
    {
      info: {
        id: "477963",
        name: "The Belgian Waffle Co.",
        cloudinaryImageId: "5116a385bac0548e06c33c08350fbf11",
        locality: "2nd Stage",
        areaName: "BTM 2nd Stage",
        costForTwo: "₹200 for two",
        cuisines: ["Waffle", "Desserts", "Ice Cream"],
        avgRating: 4.3,
        veg: true,
        parentId: "2233",
        avgRatingString: "4.3",
        totalRatingsString: "1K+",
        deliveryTime: 32,
      },
    },
    {
      info: {
        id: "643652",
        name: "WeFit - Protein Bowls, Salads & Sandwiches",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/23/8162aab2-4ccd-431e-8163-ad18749b95f5_643652.JPG",
        locality: "16TH MAIN",
        areaName: "BTM",
        costForTwo: "₹250 for two",
        cuisines: ["Healthy Food", "Salads", "Keto", "Snacks"],
        avgRating: 4.4,
        parentId: "355285",
        avgRatingString: "4.4",
        totalRatingsString: "100+",
        deliveryTime: 35,
      },
    },
    {
      info: {
        id: "750212",
        name: "Daily Kitchen - Homely Meals",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/19/4ec6a5b6-7c8d-4e10-b8a3-317922e419da_750212.JPG",
        locality: "2nd stage",
        areaName: "BTM Layout",
        costForTwo: "₹400 for two",
        cuisines: ["Home Food", "Indian", "North Indian", "Thalis"],
        avgRating: 4.3,
        parentId: "444382",
        avgRatingString: "4.3",
        totalRatingsString: "50+",
        deliveryTime: 30,
      },
    },
    {
      info: {
        id: "390045",
        name: "NH1 Bowls - Highway To North",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/5/18/8dd09eab-b40e-43ed-b46d-c88f50e450a3_390045.JPG",
        locality: "2nd stage",
        areaName: "Btm Layout",
        costForTwo: "₹250 for two",
        cuisines: ["North Indian", "Punjabi", "Home Food"],
        avgRating: 4.6,
        parentId: "22452",
        avgRatingString: "4.6",
        totalRatingsString: "100+",
        deliveryTime: 30,
      },
    },
    {
      info: {
        id: "374525",
        name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
        cloudinaryImageId: "npp2m7tuszixwcc69pqd",
        locality: "2nd Stage",
        areaName: "Btm Layout",
        costForTwo: "₹300 for two",
        cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
        avgRating: 4.6,
        veg: true,
        parentId: "582",
        avgRatingString: "4.6",
        totalRatingsString: "1K+",
        deliveryTime: 20,
      },
    },
    {
      info: {
        id: "758321",
        name: "NIC Ice Creams",
        cloudinaryImageId: "5bbe809ee274743ba5e09eab110cd813",
        locality: "MICO Employees Grinirman",
        areaName: "BTM layout",
        costForTwo: "₹120 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.9,
        veg: true,
        parentId: "6249",
        avgRatingString: "4.9",
        totalRatingsString: "10+",
        deliveryTime: 16,
      },
    },
    {
      info: {
        id: "590119",
        name: "Bakingo",
        cloudinaryImageId:
          "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/24/11e95f9e-ba33-472c-85ae-ed6d5c289992_590119.JPG",
        locality: "1st  Stage",
        areaName: "BTM Layout",
        costForTwo: "₹299 for two",
        cuisines: ["Bakery", "Desserts", "Beverages", "Snacks"],
        avgRating: 4.3,
        parentId: "3818",
        avgRatingString: "4.3",
        totalRatingsString: "1K+",
        deliveryTime: 27,
      },
    },
    {
      info: {
        id: "399138",
        name: "Aubree",
        cloudinaryImageId: "65faa4b5046cb2215fe285a8b96c9bd7",
        locality: "JP Nagar",
        areaName: "JP Nagar",
        costForTwo: "₹700 for two",
        cuisines: ["Bakery", "Italian", "Snacks", "Desserts"],
        avgRating: 4.5,
        parentId: "3807",
        avgRatingString: "4.5",
        totalRatingsString: "1K+",
        deliveryTime: 33,
      },
    },
    {
      info: {
        id: "108097",
        name: "Ambur Star Briyani Since 1890",
        cloudinaryImageId: "yktanq9i7yfjrixaghuj",
        locality: "2nd Stage",
        areaName: "BTM Layout",
        costForTwo: "₹500 for two",
        cuisines: ["Biryani", "Chettinad", "Andhra", "Beverages", "Seafood"],
        avgRating: 4.3,
        parentId: "21400",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        deliveryTime: 21,
      },
    },
    {
      info: {
        id: "558760",
        name: "HRX by EatFit",
        cloudinaryImageId: "d8d85afa5c5e92461d30ff2ca867a587",
        locality: "2nd Stage",
        areaName: "BTM Layout",
        costForTwo: "₹450 for two",
        cuisines: ["Healthy Food", "Salads", "Keto", "Pastas"],
        avgRating: 4.3,
        parentId: "335529",
        avgRatingString: "4.3",
        totalRatingsString: "100+",
        deliveryTime: 35,
      },
    },
  ];